### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by directwave** [pipelka/vdr-plugin-robotv#1]
HI,

After following [this](http://www.linuxtv.org/vdrwiki/index.php/Plugin_Installation) tutorial in installing addons to vdr, I have been unable to get pat:

cd ../..
make plugins

all plugins in the ../src compile correctly apart from robotv. The printout at the end is simply 'failed to install ..  robotv'.

Any ideas?

Thanks in advance.

Lubuntu 15.10

**Comment by pipelka** [comment]
Please provide more detailed information.
I'm unable to guess what might be the cause. A complete log may help to understand what happens.

**Comment by directwave** [comment]
Hi, this is the error in detail when compiling.

I have searched the directories for a video config file to amend the default Video directory. the only thing i found was for the timeshift location. I did go into config.cpp but couldnt find anything i'd be happy changeing without consultation.

Thank again :+1: 

**\* Plugin robotv:
CXX src/config/config.cpp
src/config/config.cpp: In member function ‘void RoboTVServerConfig::Load()’:
src/config/config.cpp:40:32: error: ‘cVideoDirectory’ has not been declared
     LiveQueue::setTimeShiftDir(cVideoDirectory::Name());
                                ^
Makefile:126: recipe for target 'src/config/config.o' failed
make[1]: **\* [src/config/config.o] Error 1

**Comment by pipelka** [comment]
You need VDR 2.2.0.
I'll add this requirement to the readme.

**Comment by directwave** [comment]
I have installed 2.2.0 and now get this error.

**\* Plugin robotv:
CXX src/robotv/robotvclient.cpp
In file included from /usr/include/c++/5/deque:64:0,
                 from /usr/include/c++/5/queue:60,
                 from src/robotv/robotvclient.h:30,
                 from src/robotv/robotvclient.cpp:50:
/usr/include/c++/5/bits/stl_deque.h: In instantiation of ‘void std::_Deque_base<_Tp, _Alloc>::_Deque_impl::_M_swap_data(std::_Deque_base<_Tp, _Alloc>::_Deque_impl&) [with _Tp = MsgPacket_; _Alloc = std::allocator<MsgPacket_>]’:
/usr/include/c++/5/bits/stl_deque.h:514:4:   required from ‘std::_Deque_base<_Tp, _Alloc>::_Deque_base(std::_Deque_base<_Tp, _Alloc>&&, std::true_type) [with _Tp = MsgPacket_; _Alloc = std::allocator<MsgPacket_>; std::true_type = std::integral_constant<bool, true>]’
/usr/include/c++/5/bits/stl_deque.h:519:61:   required from ‘std::_Deque_base<_Tp, _Alloc>::_Deque_base(std::_Deque_base<_Tp, _Alloc>&&) [with _Tp = MsgPacket_; _Alloc = std::allocator<MsgPacket_>]’
/usr/include/c++/5/bits/stl_deque.h:957:29:   required from ‘std::deque<_Tp, _Alloc>::deque(std::deque<_Tp, _Alloc>&&) [with _Tp = MsgPacket_; _Alloc = std::allocator<MsgPacket_>]’
/usr/include/c++/5/bits/stl_queue.h:146:25:   required from ‘std::queue<_Tp, _Sequence>::queue(_Sequence&&) [with _Tp = MsgPacket_; _Sequence = std::deque<MsgPacket_, std::allocator<MsgPacket*> >]’
src/robotv/robotvclient.cpp:56:27:   required from here
/usr/include/c++/5/bits/stl_deque.h:578:8: error: call of overloaded ‘swap(std::_Deque_base<MsgPacket*, std::allocator<MsgPacket*> >::iterator&, std::_Deque_base<MsgPacket*, std::allocator<MsgPacket*> >::iterator&)’ is ambiguous
    swap(this->_M_start, __x._M_start);
        ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/stl_tree.h:63,
                 from /usr/include/c++/5/map:60,
                 from src/robotv/robotvclient.cpp:30:
/usr/include/c++/5/bits/move.h:176:5: note: candidate: void std::swap(_Tp&, _Tp&) [with _Tp = std::_Deque_iterator<MsgPacket*, MsgPacket*&, MsgPacket**>]
     swap(_Tp& __a, _Tp& __b)
     ^
In file included from /home/jamie/vdr-2.2.0/include/vdr/i18n.h:14:0,
                 from /home/jamie/vdr-2.2.0/include/vdr/config.h:19,
                 from /home/jamie/vdr-2.2.0/include/vdr/channels.h:13,
                 from /home/jamie/vdr-2.2.0/include/vdr/recording.h:14,
                 from src/robotv/robotvclient.cpp:33:
/home/jamie/vdr-2.2.0/include/vdr/tools.h:57:31: note: candidate: void swap(T&, T&) [with T = std::_Deque_iterator<MsgPacket*, MsgPacket*&, MsgPacket**>]
 template<class T> inline void swap(T &a, T &b) { T t = a; a = b; b = t; }
                               ^
In file included from /usr/include/c++/5/deque:64:0,
                 from /usr/include/c++/5/queue:60,
                 from src/robotv/robotvclient.h:30,
                 from src/robotv/robotvclient.cpp:50:
/usr/include/c++/5/bits/stl_deque.h:579:8: error: call of overloaded ‘swap(std::_Deque_base<MsgPacket*, std::allocator<MsgPacket*> >::iterator&, std::_Deque_base<MsgPacket*, std::allocator<MsgPacket*> >::iterator&)’ is ambiguous
    swap(this->_M_finish, __x._M_finish);
        ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/stl_tree.h:63,
                 from /usr/include/c++/5/map:60,
                 from src/robotv/robotvclient.cpp:30:
/usr/include/c++/5/bits/move.h:176:5: note: candidate: void std::swap(_Tp&, _Tp&) [with _Tp = std::_Deque_iterator<MsgPacket*, MsgPacket*&, MsgPacket**>]
     swap(_Tp& __a, _Tp& __b)
     ^
In file included from /home/jamie/vdr-2.2.0/include/vdr/i18n.h:14:0,
                 from /home/jamie/vdr-2.2.0/include/vdr/config.h:19,
                 from /home/jamie/vdr-2.2.0/include/vdr/channels.h:13,
                 from /home/jamie/vdr-2.2.0/include/vdr/recording.h:14,
                 from src/robotv/robotvclient.cpp:33:
/home/jamie/vdr-2.2.0/include/vdr/tools.h:57:31: note: candidate: void swap(T&, T&) [with T = std::_Deque_iterator<MsgPacket*, MsgPacket*&, MsgPacket**>]
 template<class T> inline void swap(T &a, T &b) { T t = a; a = b; b = t; }
                               ^
In file included from /usr/include/c++/5/deque:64:0,
                 from /usr/include/c++/5/queue:60,
                 from src/robotv/robotvclient.h:30,
                 from src/robotv/robotvclient.cpp:50:
/usr/include/c++/5/bits/stl_deque.h:580:8: error: call of overloaded ‘swap(MsgPacket**_&, MsgPacket**_&)’ is ambiguous
    swap(this->_M_map, __x._M_map);
        ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/stl_tree.h:63,
                 from /usr/include/c++/5/map:60,
                 from src/robotv/robotvclient.cpp:30:
/usr/include/c++/5/bits/move.h:176:5: note: candidate: void std::swap(_Tp&, _Tp&) [with _Tp = MsgPacket**_]
     swap(_Tp& __a, _Tp& __b)
     ^
In file included from /home/jamie/vdr-2.2.0/include/vdr/i18n.h:14:0,
                 from /home/jamie/vdr-2.2.0/include/vdr/config.h:19,
                 from /home/jamie/vdr-2.2.0/include/vdr/channels.h:13,
                 from /home/jamie/vdr-2.2.0/include/vdr/recording.h:14,
                 from src/robotv/robotvclient.cpp:33:
/home/jamie/vdr-2.2.0/include/vdr/tools.h:57:31: note: candidate: void swap(T&, T&) [with T = MsgPacket**_]
 template<class T> inline void swap(T &a, T &b) { T t = a; a = b; b = t; }
                               ^
Makefile:126: recipe for target 'src/robotv/robotvclient.o' failed
make[1]: **\* [src/robotv/robotvclient.o] Error 1

I appreciate any help you can afford.

Kind regards

**Comment by pipelka** [comment]
Which gcc version are you using?
