### ISSUE TITLE
Feature request: Option to disable satip EIT scan

### ISSUE THREAD

**Issue by localhosthack0r** [pipelka/vdr-plugin-robotv#11]
Hi @pipelka 
thank you very much for this great vdr plugin, docker container and the Android TV app.
Great work! :-)

Would it be possible to add an option for the docker to disable the EIT scan in the satip plugin?
I tried it via setup.conf entry
satip.EnableEITScan = 0
but the setup.conf is overwritten when starting/stopping the docker. So this does not work. 

I want to achive that, when robotv is not used, the satip devices / tuners in the server get released. My channels.conf is quite big, because I am using four satellite positions and the EIT scan takes really really long.
Would live with the drawback, that EPG information in Andoid TV channels view is not up to date, until swichting to a channel.

Thanks a lot!

**Comment by pipelka** [comment]
Great to see that it's working. I didn't test it.
Not a big deal, ... ;-)
