### ISSUE TITLE
typo in docker command line?

### ISSUE THREAD

**Issue by koendv** [pipelka/vdr-plugin-robotv#15]
Thank you for this software. I'm using
```
docker run --rm -ti --cap-add=SYS_NICE -e SATIP_ENABLE=1 -v /srv/vdr:/data -v /srv/video:/video --net=host pipelka/robotv:arm64v8-latest   
```
Using ```-e SATIP_ENABLE = 1``` (with spaces) gives reference error.

A question: is there a list of known working setups? Android TV box,  Android version, minimum memory requirements?

**Comment by pipelka** [comment]
Yes. That's wrong.
Fixed the typo's. Thanks.

About requirements:
You should see the app in the Play Store on any supported Android TV device.

**Comment by koendv** [comment]
I understand what you are trying to say; but sometimes roboTV is supported but does not show up in Google Play.

On my TV (Hitachi 43hak5751, a rebranded Vestel) roboTV does not show up in Play Store. 
I tried to load roboTV app by browsing to https://play.google.com/store/apps/details?id=org.robotv.robotv 
but got the message "This app is not available in your country". (I'm living in Madrid, Spain).
So I took an Android tablet, downloaded the roboTV apk from github to the tablet, and transferred the apk from tablet to Android tv with the "Send files to TV" app. The roboTV app installed without problems, and works fine.

**Comment by pipelka** [comment]
Ahh. Ok. I see.
It isn't released world-wide. Spain is currently not on the list.
I will add Spain.

**Comment by pipelka** [comment]
Should pop up in the Play Store also in Spain now.

**Comment by pipelka** [comment]
FYI, I just got a message that the counrty change is now online.

**Comment by koendv** [comment]
"robotv" is now visible in the Play Store here. Thank you for this app.

koen
