### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by thiroxx** [pipelka/vdr-plugin-robotv#2]
Hello, I cant compile the Plugin with different GCC versions from 4.9 to 6

`src/live/livestreamer.cpp: In member function ‘int LiveStreamer::switchChannel(const cChannel*)’:
src/live/livestreamer.cpp:104:26: error: ‘Timers’ was not declared in this scope
         for(cTimer* ti = Timers.First(); ti; ti = Timers.Next(ti)) {
                          ^
src/live/livestreamer.cpp: In member function ‘virtual void LiveStreamer::Receive(const uchar*, int)’:
src/live/livestreamer.cpp:421:36: error: invalid conversion from ‘const uchar* {aka const unsigned char*}’ to ‘uint8_t* {aka unsigned char*}’ [-fpermissive]
     m_demuxers.processTsPacket(Data);
                                    ^
In file included from ./src/live/livestreamer.h:35:0,
                 from ./src/robotv/controllers/streamcontroller.h:30,
                 from ./src/robotv/robotvclient.h:42,
                 from src/live/livestreamer.cpp:38:
./src/demuxer/demuxerbundle.h:52:10: note:   initializing argument 1 of ‘bool DemuxerBundle::processTsPacket(uint8_t*) const’
     bool processTsPacket(uint8_t* packet) const;
          ^
Makefile:128: die Regel für Ziel „src/live/livestreamer.o“ scheiterte
make: *** [src/live/livestreamer.o] Fehler 1
`

**Comment by pipelka** [comment]
Which version do you want to build ?
Is this the full error message ?
Is your vdr compile environment set up properly (only vdr 2.2 currently supported) ?

**Comment by thiroxx** [comment]
Sorry my fault, tryd latest VDR Dev Version. You can close this.
