### ISSUE TITLE
Fehler - Verbindung zum Server fehlgeschlagen

### ISSUE THREAD

**Issue by hoppel118** [pipelka/vdr-plugin-robotv#3]
Hello pipelka,

I use vdr since some years now, mainly with vnsi and kodi16/17 on windows 10 machines and with libreelec from wrxtasy on an odroid c2.

Now I want to go the next step and use all the apps like netflix, amazon, red bull tv and robotv with my linving room media center. ;-)

Two weeks ago I bought an nvidia shield. Everything is fine, but I do not get your robotv app to work. SPMC with vnsi-addon works great on the same nvidia shield.

I compiled your vdr-plugin-robotv from git master on my debian jessie vdr without any errors. If I have a look at the vdr version, I also see the active robotv plugin.

```
root@omv:/usr/src/vdr/vdr-plugin-robotv# vdr -V
vdr (2.2.0/2.2.0) - The Video Disk Recorder
epgsearch (1.0.1.beta5) - search the EPG for repeats and more
conflictcheckonly (0.0.1) - Direct access to epgsearch's conflict check menu
vnsiserver (1.3.1) - VDR-Network-Streaming-Interface (VNSI) Server
live (0.3.0) - Live Interactive VDR Environment
epgsearchonly (0.0.1) - Direct access to epgsearch's search menu
robotv (0.9.102) - roboTV Server
quickepgsearch (0.0.1) - Quick search for broadcasts
```

After compiling the plugin, I compiled the robotv app with andorid studio and sideloaded the apk to the shield. So far, so good. I can start the app and it's possible to make some settings (robotv server address, ac3, timeshift, etc.). 

But I constantly (every 6 sec.) get a message: "Fehler - Verbindung zum server fehlgeschlagen".

I don't know what else to do. Where do I find the "allowed_hosts.conf" after compiling your vdr-plugin? Any other settings I have to do?

Greetings Hoppel

**Comment by pipelka** [comment]
It seems that's a common issue. Sould simplify this.
Ok. Usually the allows_hosts.conf is found here (but depends on your installation):
<pre>
/etc/vdr/plugins/robotv/allowed_hosts.conf
</pre>

Put into that file the ip-address of your clients (and or subnets). You can also simple put
<pre>
0.0.0.0/0
</pre>
into it to allow any host to connect.

**Comment by pipelka** [comment]
Another thing to mention:
You also have to put the "robotv.conf" file (from the config directory in the source distribution) into that directory (/etc/vdr/plugins/robotv).

Need to write a small HOW-TO on this (but it's basically the same as with the xvdr plugin), ...

**Comment by hoppel118** [comment]
OK, I didn't do anything special with my installation. I use the vdr packages from e-tobi's repo.

The following directory didn't exist after compilation:

`/etc/vdr/plugins/robotv/`

So, I generated that directory and copied the file from ".../src/vdr-plugin-robotv/config/allowd_hosts.conf" to "/etc/vdr/plugins/robotv/allowed_hosts.conf". The file has the following content:

```
#127.0.0.1             # always accept localhost
#10.11.11.0/24         # any host on the local net
#204.152.189.113      # a specific host
0.0.0.0/0            # any host on any net (USE THIS WITH CARE!)
```

But it still doesn't work.

**Comment by pipelka** [comment]
I know "doesn't work" is the common failure description. 
Please restart your vdr and watch the log for connection requests from you client.
Post the log snippet with the connection attempt.

**Comment by hoppel118** [comment]
OK, I will check, Copied the files to the place you mentioned, but it also doesn't work. It looks the following way now:

```
# ls -l /etc/vdr/plugins/robotv/
insgesamt 8
-rw-r--r-- 1 root root  470 Dez 11 15:22 allowed_hosts.conf
-rw-r--r-- 1 root root 1115 Dez 11 15:30 robotv.conf
```

here is the snippet from log file after I stopped the vdr:

```
Dec 11 15:37:26 omv systemd[1]: Stopped Video Disk Recorder.
Dec 11 15:37:26 omv systemd[1]: Unit vdr.service entered failed state.
Dec 11 15:39:01 omv CRON[24686]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Dec 11 15:39:03 omv systemd[1]: Starting Video Disk Recorder...
Dec 11 15:39:03 omv vdr: [24769] [live] INFO: validating server ip '0.0.0.0'
Dec 11 15:39:03 omv vdr[24769]: INFO: validating live server ip '0.0.0.0'
Dec 11 15:39:03 omv systemd[1]: Started Video Disk Recorder.
Dec 11 15:39:03 omv vdr: [24784] [live] INFO: attempt to listen on ip = '0.0.0.0'
Dec 11 15:39:03 omv vdr: [24784] [live] ERROR: Unable to load cert/key (/var/lib/vdr/plugins/live/live.pem//var/lib/vdr/plugins/live/live-key.pem): Datei oder Verzeichnis nicht$
Dec 11 15:39:03 omv vdr: [24769] ERROR: no OSD provider available - using dummy OSD!
```

The "Unit vdr.service entered failed state" seems to be new and consistent for every vdr stop. I can't see any connection request from the shield. Which loglevel do I need?

Thanks

**Comment by pipelka** [comment]
The default loglevel is ok.
Please scan the log for something like that:
<pre>
Dec 11 14:54:13 darth vdr: [7323] roboTV: Client XXX.XXX.XXX.XXX:49810 with ID 143 connected.
Dec 11 14:54:13 darth vdr: [9534] roboTV: Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
</pre>

**Comment by hoppel118** [comment]
No, nothing. nano says: "[ „roboTV“ nicht gefunden ]", if I search for "roboTV" in the syslog. There are no such messages.

**Comment by pipelka** [comment]
Well then the roboTV plugin isn't loaded.
There should be at least a message that the plugin has been started.

**Comment by hoppel118** [comment]
hm..., what do I have to do to load the plugin?

Here is the compile procedure:

```
root@omv:~# cd /usr/src/vdr/
root@omv:/usr/src/vdr# git clone https://github.com/pipelka/vdr-plugin-robotv
Klone nach 'vdr-plugin-robotv'...
remote: Counting objects: 4513, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 4513 (delta 4), reused 0 (delta 0), pack-reused 4498
Empfange Objekte: 100% (4513/4513), 2.83 MiB | 2.47 MiB/s, Fertig.
Löse Unterschiede auf: 100% (3481/3481), Fertig.
Prüfe Konnektivität... Fertig.
root@omv:/usr/src/vdr# cd vdr-plugin-robotv/
root@omv:/usr/src/vdr/vdr-plugin-robotv# make
CXX src/config/config.cpp
CXX src/db/database.cpp
CXX src/db/storage.cpp
CXX src/demuxer/demuxer.cpp
CXX src/demuxer/demuxer_ADTS.cpp
CXX src/demuxer/demuxer_LATM.cpp
CXX src/demuxer/demuxer_AC3.cpp
CXX src/demuxer/demuxer_H264.cpp
CXX src/demuxer/demuxer_H265.cpp
CXX src/demuxer/demuxer_MPEGAudio.cpp
CXX src/demuxer/demuxer_MPEGVideo.cpp
CXX src/demuxer/demuxer_PES.cpp
CXX src/demuxer/demuxer_Subtitle.cpp
CXX src/demuxer/parser.cpp
CXX src/demuxer/streambundle.cpp
CXX src/demuxer/demuxerbundle.cpp
CXX src/demuxer/streaminfo.cpp
CXX src/epg/epghandler.cpp
CXX src/live/channelcache.cpp
CXX src/live/livequeue.cpp
CXX src/live/livestreamer.cpp
CXX src/net/msgpacket.cpp
CXX src/net/os-config.cpp
CXX src/recordings/artwork.cpp
CXX src/recordings/recordingscache.cpp
CXX src/recordings/packetplayer.cpp
CXX src/recordings/recplayer.cpp
CXX src/scanner/wirbelscan.cpp
CXX src/tools/hash.cpp
CXX src/tools/recid2uid.cpp
CXX src/tools/time.cpp
CXX src/tools/urlencode.cpp
CXX src/tools/utf8conv.cpp
CXX src/robotv/controllers/streamcontroller.cpp
CXX src/robotv/controllers/recordingcontroller.cpp
CXX src/robotv/controllers/channelcontroller.cpp
CXX src/robotv/controllers/timercontroller.cpp
CXX src/robotv/controllers/moviecontroller.cpp
CXX src/robotv/controllers/logincontroller.cpp
CXX src/robotv/controllers/epgcontroller.cpp
CXX src/robotv/controllers/artworkcontroller.cpp
CXX src/robotv/svdrp/channelcmds.cpp
CXX src/robotv/robotv.cpp
CXX src/robotv/robotvclient.cpp
CXX src/robotv/robotvserver.cpp
CXX src/robotv/robotvchannels.cpp
CC src/db/sqlite3.c
LINK libvdr-robotv.so
root@omv:/usr/src/vdr/vdr-plugin-robotv# make install
install -D libvdr-robotv.so /usr/lib/vdr/plugins/libvdr-robotv.so.2.2.0
root@omv:/usr/src/vdr/vdr-plugin-robotv# ls -l /etc/vdr/plugins/robotv/
insgesamt 8
-rw-r--r-- 1 root root  470 Dez 11 15:22 allowed_hosts.conf
-rw-r--r-- 1 root root 1115 Dez 11 15:30 robotv.conf
```

That is all I did.

**Comment by pipelka** [comment]
Thats all fine. There must be a configuration file of your vdr distribution defining which plugins get loaded.

**Comment by hoppel118** [comment]
Thanks for your help. I really appreciate it. Found the following link, but don't know what to at the moment:

https://e-tobi.net/blog/2015/09/04/vdr-paket-updates-fur-debian-jessie

I generated an empty file under "/etc/vdr/conf.avail" for the robotv plugin and a symlink to that file under "/etc/vdr/conf.d", but it still doesn't work. 

I am going to write a thread in the vdr forum. Please leave the issue open. I will report back, if it's solved or I need your help again. 

Ich wünsche dir einen schönen dritten Advent! ;-) Danke und Gruß

**Comment by pipelka** [comment]
Please try the following:
<pre>
# rm /etc/vdr/conf.avail/robotv.conf
# echo "[robotv]" > /etc/vdr/conf.avail/robotv.conf
</pre>

then restart your vdr.

**Comment by hoppel118** [comment]
The connection is established. Great, thanks for this hint. I still don't see any welcome messages in the syslog. But I can see the following error message:

`Dec 11 20:41:21 omv vdr: [1764] roboTV-Error: SQLite: SQL logic error or missing database`

Do I need to install sql? What are the dependencies exactly? At the moment I only see my recordings in the roboTV application. No epg, live channels and so on.

I can do further tests in the middle of the week.

Thanks and Greetings Hoppel

**Comment by pipelka** [comment]
roboTV needs to create a sqlite database in the cache directory.
The cache directory depends on your distribution but is usually
located at "/var/cache/vdr/plugins/robotv". Write permissions are
needed.

roboTV integrates seamlessly into the Android TV OS. So all
TV interaction is done in the "Live Channels" app. Open Live
Channels. Go to the settings and import your channels.

As i found a serious bug today i would suggest to update your roboTV
client to the current "master".

**Comment by hoppel118** [comment]
Ok, thanks for the information. I will check it in the middle of the week and report back. Now I am on a short business trip.

Greetings Hoppel

**Comment by hoppel118** [comment]
OK, made some short tests. I see imported my channel list and it's possible to watch live channels. 

By the way, my log-level was wrong, it was "1 - show only errors". Now I configured log level "2" and see the following entries in the syslog:

```
root@omv:~# cat /var/log/syslog | grep "roboTV"
Dec 12 08:41:22 omv vdr: [18408] roboTV-Error: SQLite: SQL logic error or missing database
Dec 12 20:41:22 omv vdr: [1151] roboTV-Error: SQLite: SQL logic error or missing database
Dec 12 23:36:32 omv vdr: [5761] initializing plugin: robotv (0.9.102): roboTV Server
Dec 12 23:36:32 omv vdr: [5761] roboTV: timeshift buffersize: 1000000000 bytes
Dec 12 23:36:32 omv vdr: [5761] roboTV: Folder for TV shows: Serien
Dec 12 23:36:32 omv vdr: [5761] roboTV: Opening database: /var/cache/vdr/plugins/robotv/storage.db
Dec 12 23:36:32 omv vdr: [5761] roboTV: roboTV Server started
Dec 12 23:36:32 omv vdr: [5784] roboTV: removing outdated epg entries
Dec 12 23:36:32 omv vdr: [5784] roboTV-Error: SQLite: SQL logic error or missing database
Dec 12 23:36:32 omv vdr: [5785] roboTV: removing outdated artwork
Dec 12 23:36:32 omv vdr: [5785] roboTV: Client 10.11.11.89:18884 with ID 0 connected.
Dec 12 23:36:32 omv vdr: [5815] roboTV: Welcome client 'roboTV:dataservice' with protocol version '7' and priority 1
Dec 12 23:36:32 omv vdr: [5785] roboTV: Recordings state changed (42)
Dec 12 23:36:32 omv vdr: [5785] roboTV: Recordings state changed (63)
Dec 12 23:36:33 omv vdr: [5785] roboTV: Recordings state changed (83)
Dec 12 23:36:33 omv vdr: [5785] roboTV: Recordings state changed (103)
Dec 12 23:36:33 omv vdr: [5785] roboTV: Recordings state changed (121)
Dec 12 23:36:33 omv vdr: [5785] roboTV: Recordings state changed (133)
Dec 12 23:36:34 omv vdr: [5785] roboTV: Recordings state changed (148)
Dec 12 23:36:34 omv vdr: [5785] roboTV: Recordings state changed (158)
Dec 12 23:36:34 omv vdr: [5785] roboTV: Recordings state changed (176)
Dec 12 23:36:34 omv vdr: [5785] roboTV: Recordings state changed (198)
Dec 12 23:36:35 omv vdr: [5761] roboTV: Sending timer change request to client #0 ...
Dec 12 23:36:35 omv vdr: [5785] roboTV: Recordings state changed (216)
Dec 12 23:36:36 omv vdr: [5785] roboTV: Requesting clients to reload recordings list
Dec 12 23:36:37 omv vdr: [5761] roboTV: Sending timer change request to client #0 ...
```

There is something wrong with SQLite. If I have a look to the path you mentioned I can the the automatically generated storage.db
 
```
root@omv:~# ls -l /var/cache/vdr/plugins/robotv/storage.db
-rw-r--r-- 1 vdr vdr 47282176 Dez 12 23:41 /var/cache/vdr/plugins/robotv/storage.db
```

I don't see any epg data. The guide is completely empty. Can this be related to the sqlite error? IS the epg data stored in the database?

I am going to recompile the robotv app tomorrow, but I am not an optimist to solve the missing epg data with that new version. 

What can be done?

Greetings Hoppel

**Comment by pipelka** [comment]
The EPG shown on the client is not stored in the db (on the server). The db contains preprocessed EPG data for searching. The EPG on the client is synced in the background. An initial sync can take a very long time (every event is synced via tmdb, themoviedb and cached). If there wasn't a crash after importing the channels everything should work as expected.

**Comment by hoppel118** [comment]
Hello pipelka,

thank you very much for your help. The EPG is working as expected now. Compiled the new version of the app and installed it. It is absolutely possible that I didn't have enough patience and brought the initial sync to a crash while my first try.

Thank you for this amazing android tv app for the vdr!

Greetings Hoppel
