### ISSUE TITLE
Kein Bild bei den meisten Sky Kanälen

### ISSUE THREAD

**Issue by drahtjacke** [pipelka/vdr-plugin-robotv#9]
Hallo,

seit geraumer Zeit bekomme ich bei den meisten Sky Kanälen kein Bild mehr. Meine Vermutung ist, daß die Audioparser nicht mehr mit den aktuellen Sky Tonspuren kompatibel sind. Anbei ein log:

Das funktioniert:
Dec  6 12:44:45 pi-nas vdr: [461] ======================================
Dec  6 12:44:45 pi-nas vdr: [461] CHANNEL STREAM REQUEST
Dec  6 12:44:45 pi-nas vdr: [461] ======================================
Dec  6 12:44:45 pi-nas vdr: [461] 1 - Das Erste (S19.2E-1-1101-28106)
Dec  6 12:44:45 pi-nas vdr: [461] Preferred audio track: AC3 - deu
Dec  6 12:44:45 pi-nas vdr: [461] --------------------------------------
Dec  6 12:44:45 pi-nas vdr: [461] camslot detached
Dec  6 12:44:45 pi-nas vdr: [461] CAM 1: unassigned from device 2
Dec  6 12:44:45 pi-nas vdr: [461] LiveQueue terminated
Dec  6 12:44:45 pi-nas vdr: [461] live streamer terminated
Dec  6 12:44:45 pi-nas vdr: [461] Found available device 2
Dec  6 12:44:45 pi-nas vdr: [474] device 2 receiver thread ended (pid=440, tid=474)
Dec  6 12:44:45 pi-nas vdr: [461] Channel information found in cache
Dec  6 12:44:45 pi-nas vdr: [461] Creating demuxers
Dec  6 12:44:45 pi-nas vdr: [461] Successfully switched to channel 1 - Das Erste
Dec  6 12:44:45 pi-nas vdr: [461] done switching.
Dec  6 12:44:45 pi-nas vdr: [461] --------------------------------------
Dec  6 12:44:45 pi-nas vdr: [475] device 2 receiver thread started (pid=440, tid=475, prio=high)
Dec  6 12:44:45 pi-nas vdr: [461] Started streaming of channel Das Erste (priority 50)
Dec  6 12:44:46 pi-nas vdr: [475] demuxers ready
Dec  6 12:44:46 pi-nas vdr: [475] Stream: MPEG2VIDEO PID: 101 720x576 DAR: 1,78 FPS: 25,000 SPS/PPS/VPS: 0/0/0 bytes (parsed: yes)
Dec  6 12:44:46 pi-nas vdr: [475] Stream: AC3 PID: 106 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Dec  6 12:44:46 pi-nas vdr: [475] Stream: MPEG2AUDIO PID: 102 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Dec  6 12:44:46 pi-nas vdr: [475] Stream: MPEG2AUDIO PID: 103 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Dec  6 12:44:46 pi-nas vdr: [475] Stream: DVBSUB PID: 105 Lang: deu (parsed: yes)
Dec  6 12:44:46 pi-nas vdr: [475] processing 0 pre-queued packets
Dec  6 12:44:46 pi-nas vdr: [477] timeshift file: /run/robotv-ringbuffer-00031.data
Dec  6 12:45:25 pi-nas vdr: [458] device 1 receiver thread ended (pid=440, tid=458)
Das funktioniert nicht:
Dec  6 12:45:33 pi-nas vdr: [461] ======================================
Dec  6 12:45:33 pi-nas vdr: [461] CHANNEL STREAM REQUEST
Dec  6 12:45:33 pi-nas vdr: [461] ======================================
Dec  6 12:45:33 pi-nas vdr: [461] 49 - Sky Cinema 007 HD (C-133-13-111)
Dec  6 12:45:33 pi-nas vdr: [461] Preferred audio track: AC3 - deu
Dec  6 12:45:33 pi-nas vdr: [461] --------------------------------------
Dec  6 12:45:33 pi-nas vdr: [475] device 2 receiver thread ended (pid=440, tid=475)
Dec  6 12:45:33 pi-nas vdr: [461] LiveQueue terminated
Dec  6 12:45:33 pi-nas vdr: [461] live streamer terminated
Dec  6 12:45:33 pi-nas vdr: [461] CAM 1: assigned to device 1
Dec  6 12:45:33 pi-nas vdr: [478] device 1 receiver thread started (pid=440, tid=478, prio=high)
Dec  6 12:45:33 pi-nas vdr: [461] Found available device 1
Dec  6 12:45:33 pi-nas vdr: [453] DVBAPI: 0.0 set CAM decrypt (SID 111 (0x006F), caLm 5, HasCaDescriptors 0)
Dec  6 12:45:33 pi-nas vdr: [444] SATIP: Detected 1 RTP packet error [device 0]
Dec  6 12:45:33 pi-nas vdr: [461] Channel information found in cache
Dec  6 12:45:33 pi-nas vdr: [461] Creating demuxers
Dec  6 12:45:33 pi-nas vdr: [461] Successfully switched to channel 49 - Sky Cinema 007 HD
Dec  6 12:45:33 pi-nas vdr: [461] DVBAPI: 1.0 set CAM decrypt (SID 111 (0x006F), caLm 4, HasCaDescriptors 0)
Dec  6 12:45:33 pi-nas vdr: [461] done switching.
Dec  6 12:45:33 pi-nas vdr: [461] --------------------------------------
Dec  6 12:45:33 pi-nas vdr: [461] Started streaming of channel Sky Cinema 007 HD (priority 50)

**Comment by pipelka** [comment]
As other Channels are working I'm pretty sure this issue is *not* related to roboTV.
I'm not using Sky. I can't tell what's the problem, but a good starting point would be the dvbapi plugin. Maybe you should take a look the the dvbapi README (Point 8).

**Comment by drahtjacke** [comment]
Hallo,

das Ticket kann geschlossen werden. Nach einem Neustart meiner Fritz!Box trat das Problem nicht mehr. auf.

MfG
